### ISSUE TITLE
odd result 

### ISSUE THREAD

**Issue by StevenDaChui** [mlampros/FeatureSelection#2]
I run the code with my data
the glmnet result show only one important factor which is odd
Anyone knonw why? 
Thx a lot.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/82921940/236414476-43d5fc74-0eb1-4bac-a7bf-ceb7378aad25.png">

**Comment by mlampros** [comment]
@StevenDaChui I'm sorry for not replying earlier. 
What version of the glmnet R package did you use?
It would be wise to include the code that you used so that I can re-produce the visualization in my PC.

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case the code does not work as expected
